<?php

use Drupal\commerce\BundleFieldDefinition;

/*
 * Implements hook_entity_field_storage_info().
 *
 * Add fields to use with globalone stored card payment method type
 */

function commerce_globalone_entity_base_field_info(\Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'commerce_payment_method') {
    $fields['card_reference'] = BundleFieldDefinition::create('string')
    ->setLabel(t('Card Reference'))
    ->setDescription(t('The reference to stored card on globalone payments service'))
    ->setRequired(TRUE);
       
    return $fields;
  }	
}

